sources:
  - name: mainnet7007
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/72917/7007graph/v0.0.3_mainnet
  - name: sepolia7007
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/72917/7007graph/v0.0.2

documents:
  - ./.graphql

